### ISSUE TITLE
RFE : add code coverage report

### ISSUE THREAD

**Issue by OlivierJaquemet** [samdjstevens/java-totp#10]
This a request for enhancement regarding the build process and the indication provided in default github README page : 

- update the circleci build to add codecovergage instrumentation with jacoco 
- update README to add gadget to https://codecov.io/github/samdjstevens/java-totp/

Resources : 
https://github.com/codecov/example-java

Example of other TOTP java project with this codecoverage metrics : 
https://github.com/j256/two-factor-auth

**Comment by samdjstevens** [comment]
Thanks for the suggestion - I agree this would be a good enhancement. I'll see if I can get this into the project soon

**Comment by samdjstevens** [comment]
Fixed by #15 !

**Comment by OlivierJaquemet** [comment]
Awesome. You rock !
