### ISSUE TITLE
Discussion : why ZXing 3.3.0 ?

### ISSUE THREAD

**Issue by OlivierJaquemet** [samdjstevens/java-totp#14]
Your project's pom.xml declare a dependency to ZXing version 3.3.0 (whose javase module uses JAI Image IO 1.3.1)

ZXing updates are available : 

- 3.3.3 was release in may 2018, it uses JAI Image IO 1.4.0.
- 3.4.0 was release in may 2019, it uses JAI Image IO 1.4.0.

Is there any rational behind your choice that we should be aware of ?

**Comment by samdjstevens** [comment]
No particular reason, to be honest I probably just copied the version number from a blog post! Happy to have it upgraded to the latest if you want to make a quick PR.

**Comment by OlivierJaquemet** [comment]
I'll do that as soon as I can.

**Comment by OlivierJaquemet** [comment]
See #17

**Comment by samdjstevens** [comment]
Merged
